CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [USER_ID] INT NOT NULL, 
    [USER_NAME] NVARCHAR(50) NOT NULL, 
    [USER_SURNAME] NVARCHAR(50) NOT NULL, 
    [USER_PASSWORD] NVARCHAR(50) NOT NULL, 
    [USER_EMAIL] NVARCHAR(50) NOT NULL
)
