CREATE TABLE [dbo].[Users]
(
	[USER_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [USER_NAME] NVARCHAR(50) NOT NULL, 
    [USER_SURNAME] NVARCHAR(50) NOT NULL, 
    [USER_PASSWORD] NVARCHAR(MAX) NOT NULL, 
    [USER_EMAIL] NVARCHAR(MAX) NOT NULL
)
